{{- if .Values.monitoring }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring
  namespace: {{ include "tenant.name" . }}
  labels:
    cozystack.io/ui: "true"
    internal.cozystack.io/tenantmodule: "true"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    apps.cozystack.io/application.kind: Monitoring
    apps.cozystack.io/application.group: apps.cozystack.io
    apps.cozystack.io/application.name: monitoring
spec:
  chart:
    spec:
      chart: monitoring
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-extra
        namespace: cozy-public
      version: '>= 0.0.0-0'
  interval: 5m
  timeout: 10m
  install:
    remediation:
      retries: -1
  upgrade:
    force: true
    remediation:
      retries: -1
  valuesFrom:
  - kind: Secret
    name: cozystack-values
{{- end }}
