{{/* Lookup for namespace uid (needed for ownerReferences) */}}
{{- $existingNS := lookup "v1" "Namespace" "" .Release.Namespace }}
{{- if not $existingNS }}
{{- fail (printf "error lookup existing namespace: %s" .Release.Namespace) }}
{{- end }}

{{- if ne (include "tenant.name" .) "tenant-root" }}
{{/* Compute namespace values once for use in both Secret and labels */}}
{{- $tenantName := include "tenant.name" . }}
{{- $parentNamespace := .Values._namespace | default dict }}
{{- $parentHost := $parentNamespace.host | default "" }}

{{/* Compute host */}}
{{- $computedHost := "" }}
{{- if .Values.host }}
{{- $computedHost = .Values.host }}
{{- else if $parentHost }}
{{- $computedHost = printf "%s.%s" (splitList "-" $tenantName | last) $parentHost }}
{{- end }}

{{/* Compute service references */}}
{{- $etcd := $parentNamespace.etcd | default "" }}
{{- if .Values.etcd }}
{{- $etcd = $tenantName }}
{{- end }}

{{- $ingress := $parentNamespace.ingress | default "" }}
{{- if .Values.ingress }}
{{- $ingress = $tenantName }}
{{- end }}

{{- $monitoring := $parentNamespace.monitoring | default "" }}
{{- if .Values.monitoring }}
{{- $monitoring = $tenantName }}
{{- end }}

{{- $seaweedfs := $parentNamespace.seaweedfs | default "" }}
{{- if .Values.seaweedfs }}
{{- $seaweedfs = $tenantName }}
{{- end }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $tenantName }}
  {{- if hasPrefix "tenant-" .Release.Namespace }}
  labels:
    tenant.cozystack.io/{{ $tenantName }}: ""
    {{- $parts := splitList "-" .Release.Namespace }}
    {{- range $i, $v := $parts }}
    {{- if ne $i 0 }}
    tenant.cozystack.io/{{ join "-" (slice $parts 0 (add $i 1)) }}: ""
    {{- end }}
    {{- end }}
    {{/* Labels for network policies */}}
    namespace.cozystack.io/etcd: {{ $etcd | quote }}
    namespace.cozystack.io/ingress: {{ $ingress | quote }}
    namespace.cozystack.io/monitoring: {{ $monitoring | quote }}
    namespace.cozystack.io/seaweedfs: {{ $seaweedfs | quote }}
    namespace.cozystack.io/host: {{ $computedHost | quote }}
    alpha.kubevirt.io/auto-memory-limits-ratio: "1.0"
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Namespace
    name: {{ .Release.Namespace }}
    uid: {{ $existingNS.metadata.uid }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cozystack-values
  namespace: {{ $tenantName }}
  labels:
    reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
  values.yaml: |
    _cluster:
      {{- .Values._cluster | toYaml | nindent 6 }}
    _namespace:
      etcd: {{ $etcd | quote }}
      ingress: {{ $ingress | quote }}
      monitoring: {{ $monitoring | quote }}
      seaweedfs: {{ $seaweedfs | quote }}
      host: {{ $computedHost | quote }}
{{- end }}
