---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.backup-controller
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
  - name: default
    dependsOn:
    - cozystack.networking
    components:
    - name: backup-controller
      path: system/backup-controller
      install:
        privileged: true
        namespace: cozy-backup-controller
        releaseName: backup-controller
