---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.bootbox
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
  - name: default
    dependsOn:
    - cozystack.networking
    - cozystack.bootbox-application
    components:
    - name: bootbox
      path: system/bootbox
      install:
        privileged: true
        namespace: cozy-bootbox
        releaseName: bootbox
