---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.capi-operator
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
  - name: default
    dependsOn:
    - cozystack.networking
    components:
    - name: capi-operator
      path: system/capi-operator
      install:
        privileged: true
        namespace: cozy-cluster-api
        releaseName: capi-operator
