---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.clickhouse-operator
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
  - name: default
    dependsOn:
    - cozystack.networking
    - cozystack.prometheus-operator-crds
    components:
    - name: clickhouse-operator
      path: system/clickhouse-operator
      install:
        namespace: cozy-clickhouse-operator
        releaseName: clickhouse-operator
