---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.etcd-operator
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
  - name: default
    dependsOn:
    - cozystack.networking
    - cozystack.cert-manager
    components:
    - name: etcd-operator
      path: system/etcd-operator
      install:
        namespace: cozy-etcd-operator
        releaseName: etcd-operator
