---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.external-secrets-operator
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
  - name: default
    dependsOn:
    - cozystack.networking
    components:
    - name: external-secrets-operator
      path: system/external-secrets-operator
      install:
        namespace: cozy-external-secrets-operator
        releaseName: external-secrets-operator
