---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.foundationdb-operator
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
  - name: default
    dependsOn:
    - cozystack.networking
    - cozystack.cert-manager
    components:
    - name: foundationdb-operator
      path: system/foundationdb-operator
      install:
        namespace: cozy-foundationdb-operator
        releaseName: foundationdb-operator
