---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.grafana-operator
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
  - name: default
    dependsOn:
    - cozystack.networking
    components:
    - name: grafana-operator
      path: system/grafana-operator
      install:
        namespace: cozy-grafana-operator
        releaseName: grafana-operator
