---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.hetzner-robotlb
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
  - name: default
    dependsOn:
    - cozystack.networking
    components:
    - name: hetzner-robotlb
      path: system/hetzner-robotlb
      install:
        namespace: cozy-hetzner-robotlb
        releaseName: robotlb
