---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.kafka-operator
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
  - name: default
    dependsOn:
    - cozystack.networking
    - cozystack.prometheus-operator-crds
    components:
    - name: kafka-operator
      path: system/kafka-operator
      install:
        namespace: cozy-kafka-operator
        releaseName: kafka-operator
