---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.keycloak-operator
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
  - name: default
    dependsOn:
    - cozystack.networking
    - cozystack.keycloak
    components:
    - name: keycloak-operator
      path: system/keycloak-operator
      install:
        namespace: cozy-keycloak
        releaseName: keycloak-operator
