---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.linstor
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
  - name: default
    dependsOn:
    - cozystack.networking
    - cozystack.cert-manager
    - cozystack.victoria-metrics-operator
    - cozystack.reloader
    - cozystack.snapshot-controller
    components:
    - name: piraeus-operator
      path: system/piraeus-operator
      install:
        namespace: cozy-linstor
        releaseName: piraeus-operator
    - name: linstor
      path: system/linstor
      install:
        privileged: true
        namespace: cozy-linstor
        releaseName: linstor
        dependsOn:
        - piraeus-operator
