---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.nfs-driver
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
  - name: default
    dependsOn:
    - cozystack.networking
    components:
    - name: nfs-driver
      path: system/nfs-driver
      install:
        privileged: true
        namespace: cozy-nfs-driver
        releaseName: nfs-driver
