---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.postgres-operator
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
  - name: default
    dependsOn:
    - cozystack.networking
    - cozystack.prometheus-operator-crds
    - cozystack.cert-manager
    components:
    - name: postgres-operator
      path: system/postgres-operator
      install:
        namespace: cozy-postgres-operator
        releaseName: postgres-operator
