---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.snapshot-controller
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
  - name: default
    dependsOn:
    - cozystack.networking
    - cozystack.cert-manager
    components:
    - name: snapshot-controller
      path: system/snapshot-controller
      install:
        namespace: cozy-snapshot-controller
        releaseName: snapshot-controller
