---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.victoria-metrics-operator
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
  - name: default
    dependsOn:
    - cozystack.networking
    - cozystack.cert-manager
    components:
    - name: victoria-metrics-operator
      path: system/victoria-metrics-operator
      install:
        namespace: cozy-victoria-metrics-operator
        releaseName: victoria-metrics-operator
